### ISSUE TITLE
When running publisher, get errors in get_feeds()

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#122]
### Describe the bug

Going through predictoor.md README, when I run
```console
python pdr_backend/predictoor/main.py 1
```

Note: `SUBGRAPH_URL=http://localhost:9000/subgraphs/name/oceanprotocol/ocean-subgraph`

It fails in two possible ways. First way:
```text
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/models/feed.py", line 70, in dictToFeed
    trueval_submit_timeout=d["trueval_submit_timeout"],
                           ~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'trueval_submit_timeout'
```

I just merged a branch into main. Now it fails a different way:
```text
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/approach1/predictoor_agent1.py", line 25, in __init__
    self.feeds: Dict[str, Feed] = self.config.get_feeds()  # [addr] : Feed
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/models/base_config.py", line 42, in get_feeds
    feed_dicts = query_feed_contracts(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 28, in wrapper
    check_types(*args, **kwargs)
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 21, in check_types
    raise TypeError(
TypeError: Expected type 'typing.Optional[str]' for attribute 'owners_string' but received type '<class 'list'>')
```

### Discussion

For error 1: I'm pretty sure that I (Trent) introduced this when I introduced dictToFeed recently. It expects more data than it should have. That's where the fix lies too: to be looser about what it needs. E.g. fill in with good defaults.

### Full traceback of error 1

```text
(venv) trentmc@tlm-macbook: ~/code/pdr-backend $ python pdr_backend/predictoor/main.py 1
Traceback (most recent call last):
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/main.py", line 48, in <module>
    do_main()
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/main.py", line 31, in do_main
    do_main1()
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/approach1/main1.py", line 10, in do_main1
    p = PredictoorAgent1(config)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/approach1/predictoor_agent1.py", line 25, in __init__
    self.feeds: Dict[str, Feed] = self.config.get_feeds()  # [addr] : Feed
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/models/base_config.py", line 49, in get_feeds
    feeds = {addr: dictToFeed(feed_dict) for addr, feed_dict in feed_dicts.items()}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/models/base_config.py", line 49, in <dictcomp>
    feeds = {addr: dictToFeed(feed_dict) for addr, feed_dict in feed_dicts.items()}
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/models/feed.py", line 70, in dictToFeed
    trueval_submit_timeout=d["trueval_submit_timeout"],
                           ~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'trueval_submit_timeout'
```

### Full traceback of error 2

```text
(venv) trentmc@tlm-macbook: ~/code/pdr-backend $ python pdr_backend/predictoor/main.py 1
Traceback (most recent call last):
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/main.py", line 48, in <module>
    do_main()
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/main.py", line 31, in do_main
    do_main1()
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/approach1/main1.py", line 10, in do_main1
    p = PredictoorAgent1(config)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/predictoor/approach1/predictoor_agent1.py", line 25, in __init__
    self.feeds: Dict[str, Feed] = self.config.get_feeds()  # [addr] : Feed
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/models/base_config.py", line 42, in get_feeds
    feed_dicts = query_feed_contracts(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 28, in wrapper
    check_types(*args, **kwargs)
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 21, in check_types
    raise TypeError(
TypeError: Expected type 'typing.Optional[str]' for attribute 'owners_string' but received type '<class 'list'>')
```

**Comment by trentmc** [comment]
In the PR, I fixed error 2 by tightening up what gets passed when and where: None vs [] vs str vs list vs tuple.

**Comment by trentmc** [comment]
Wrt error 1, here's the dict that got passed into dictToFeed() right before the error:
`{'name': 'XRP/USDT', 'address': '0x2d30d9b506f8df53058674a8be8722b073edf6a5', 'symbol': 'XRP/USDT', 'seconds_per_epoch': '300', 'seconds_per_subscription': '86400', 'last_submited_epoch': 0, 'pair': 'XRP/USDT', 'timeframe': '5m', 'source': 'binance', 'base': 'XRP', 'quote': 'USDT'}`
