### ISSUE TITLE
trade_engine.py KeyError: 'TRX'

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#328]
### To reproduce

In console:
```bash
export PAIR_FILTER=TRX/USDT
python pdr_backend/simulation/runtrade.py
```

Output:
```text
Config: ['TRX'] ['binance'] 1h
data_ss=DataSS={
  csv_dir=/Users/trentmc/code/pdr-backend/csvs
  st_timestamp=timestamp=1656547200000, dt=2022-06-30 00:00:00+00:00
  fin_timestamp=timestamp=1699642978434, dt=2023-11-10 19:02:58.434000+00:00
 ...
  No file exists yet, so will fetch all data
  Aim to fetch data from start time: timestamp=1656547200000, dt=2022-06-30 00:00:00+00:00
  Fetch 1000 pts from timestamp=1656547200000, dt=2022-06-30 00:00:00+00:00
...
  Just saved df with 11971 rows to new file /Users/trentmc/code/pdr-backend/csvs/binance_TRX-USDT_1h.csv
Load csv from exchange=Binance, pair=TRX/USDT
Traceback (most recent call last):
  File "/Users/trentmc/code/pdr-backend/pdr_backend/simulation/runtrade.py", line 74, in <module>
    trade_engine.run()
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/simulation/trade_engine.py", line 86, in run
    self.run_one_iter(test_i, hist_df)
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.11/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/simulation/trade_engine.py", line 127, in run_one_iter
    self._buy(curprice, self.trade_ss.buy_amt_usd)
  File "/Users/trentmc/code/pdr-backend/pdr_backend/simulation/trade_engine.py", line 191, in _buy
    self.holdings[self.tokcoin] += tokcoin_amt_recd
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'TRX'
```

**Comment by trentmc** [comment]
Fixed in PR #329 // commit https://github.com/oceanprotocol/pdr-backend/commit/e7112fcad0245f49067151a71220509fb28a1f76
