### ISSUE TITLE
[Bug] test_FixedRate - ValueError: transaction can't be replaced, mining already started

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#520]
### Description

I encountered this in a routine CI.

```text
=========================== short test summary info ============================
ERROR pdr_backend/contract/test/test_fixed_rate.py::test_FixedRate - ValueError: {'message': "transaction can't be replaced, mining has already started. (please open an issue with reproduction steps: https://github.com/trufflesuite/ganache/issues/new)", 'stack': "Error: transaction can't be replaced, mining has already started. (please open an issue with reproduction steps: [https://github.com/trufflesuite/ganache/issues/new)\n](https://github.com/trufflesuite/ganache/issues/new)/n)    at shouldReplace (/app/dist/node/1.js:2:185530)\n    at TransactionPool.prepareTransaction (/app/dist/node/1.js:2:188093)", 'code': -32003}
```

Note: this is likely the same root issue as #546

### Full traceback

From [this log](https://github.com/oceanprotocol/pdr-backend/actions/runs/7487703067/job/20380630048?pr=518). (It's in a PR that had small changes completely unrelated to FixedRate).

```text
==================================== ERRORS ====================================
_______________________ ERROR at setup of test_FixedRate _______________________

    @pytest.fixture(scope="module")  # "module" = invoke once per test module
    def predictoor_contract():
        w3p = _web3_pp()
        w3c = w3p.web3_config
>       _, _, _, _, logs = publish_asset(
            s_per_epoch=S_PER_EPOCH,
            s_per_subscription=S_PER_EPOCH * 24,
            base="ETH",
            quote="USDT",
            source="kraken",
            timeframe="5m",
            trueval_submitter_addr=w3c.owner,
            feeCollector_addr=w3c.owner,
            rate=3,
            cut=0.2,
            web3_pp=w3p,
        )

pdr_backend/conftest_ganache.py:64: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/enforce_typing/decorator.py:29: in wrapper
    return func(*args, **kwargs)
pdr_backend/publisher/publish_asset.py:68: in publish_asset
    logs_nft, logs_erc = factory.createNftWithErc20WithFixedRate(
pdr_backend/contract/erc721_factory.py:20: in createNftWithErc20WithFixedRate
    tx = self.contract_instance.functions.createNftWithErc20WithFixedRate(
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/contract/contract.py:323: in transact
    return transact_with_contract_function(
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/contract/utils.py:172: in transact_with_contract_function
    txn_hash = w3.eth.send_transaction(transact_transaction)
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/eth/eth.py:381: in send_transaction
    return self._send_transaction(transaction)
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/module.py:75: in caller
    result = w3.manager.request_blocking(
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/manager.py:325: in request_blocking
    return self.formatted_response(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

response = {'error': {'code': -32003, 'message': "transaction can't be replaced, mining has already started. (please open an issu.../1.js:2:185530)\n    at TransactionPool.prepareTransaction (/app/dist/node/1.js:2:188093)"}, 'id': 4, 'jsonrpc': '2.0'}
params = ({'data': '0xd282aa860000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000... '0xe2DD09d719Da89e5a3D0F2549c7E24566e947260', 'gasPrice': '0x0', 'to': '0xF152cF3c67dFD41a317eAe8fAc0e1e8E98724A13'},)
error_formatters = <cyfunction identity at 0x7fab44436e10>
null_result_formatters = <cyfunction identity at 0x7fab44436e10>

    @staticmethod
    def formatted_response(
        response: RPCResponse,
        params: Any,
        error_formatters: Optional[Callable[..., Any]] = None,
        null_result_formatters: Optional[Callable[..., Any]] = None,
    ) -> Any:
        # jsonrpc is not enforced (as per the spec) but if present, it must be 2.0
        if "jsonrpc" in response and response["jsonrpc"] != "2.0":
            _raise_bad_response_format(
                response, 'The "jsonrpc" field must be present with a value of "2.0"'
            )
    
        # id is not enforced (as per the spec) but if present, it must be a
        # string or integer
        # TODO: v7 - enforce id per the spec
        if "id" in response:
            response_id = response["id"]
            # id is always None for errors
            if response_id is None and "error" not in response:
                _raise_bad_response_format(
                    response, '"id" must be None when an error is present'
                )
            elif not isinstance(response_id, (str, int, type(None))):
                _raise_bad_response_format(response, '"id" must be a string or integer')
    
        # Response may not include both "error" and "result"
        if "error" in response and "result" in response:
            _raise_bad_response_format(
                response, 'Response cannot include both "error" and "result"'
            )
    
        # Format and validate errors
        elif "error" in response:
            error = response.get("error")
            # Raise the error when the value is a string
            if error is None or isinstance(error, str):
                raise ValueError(error)
    
            # Errors must include an integer code
            code = error.get("code")
            if not isinstance(code, int):
                _raise_bad_response_format(response, "error['code'] must be an integer")
            elif code == METHOD_NOT_FOUND:
                raise MethodUnavailable(error)
    
            # Errors must include a message
            if not isinstance(error.get("message"), str):
                _raise_bad_response_format(
                    response, "error['message'] must be a string"
                )
    
            apply_error_formatters(error_formatters, response)
    
>           raise ValueError(error)
E           ValueError: {'message': "transaction can't be replaced, mining has already started. (please open an issue with reproduction steps: https://github.com/trufflesuite/ganache/issues/new)", 'stack': "Error: transaction can't be replaced, mining has already started. (please open an issue with reproduction steps: https://github.com/trufflesuite/ganache/issues/new)\n    at shouldReplace (/app/dist/node/1.js:2:[185](https://github.com/oceanprotocol/pdr-backend/actions/runs/7487703067/job/20380630048?pr=518#step:8:186)530)\n    at TransactionPool.prepareTransaction (/app/dist/node/1.js:2:[188](https://github.com/oceanprotocol/pdr-backend/actions/runs/7487703067/job/20380630048?pr=518#step:8:189)093)", 'code': -3[200](https://github.com/oceanprotocol/pdr-backend/actions/runs/7487703067/job/20380630048?pr=518#step:8:201)3}

/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/manager.py:288: ValueError
```

**Comment by trentmc** [comment]
This issue was also reported in #630 (duplicate). Closing it there.
