### ISSUE TITLE
[YAML] Dfbuyer fails due to missing attribute in web3_config

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/pdr-backend#530]
`Checking allowance...
Traceback (most recent call last):
  File "/home/calina/pdr-backend/./pdr", line 6, in <module>
    cli_module._do_main()
  File "/home/calina/pdr-backend/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/calina/pdr-backend/pdr_backend/cli/cli_module.py", line 44, in _do_main
    func(args)
  File "/home/calina/pdr-backend/pdr_backend/cli/cli_module.py", line 149, in do_dfbuyer
    agent = DFBuyerAgent(ppss)
  File "/home/calina/pdr-backend/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/calina/pdr-backend/pdr_backend/dfbuyer/dfbuyer_agent.py", line 55, in __init__
    ppss.web3_pp.web3_config.owner,
AttributeError: 'Web3Config' object has no attribute 'owner'`

getting this when running dfbuyer on development network. I've checked the file history and it's not in the first few recent changes. So I'm documenting this here instead.

**Comment by calina-c** [comment]
Forgot to export the private key. My bad, closing this.
